version: '3'

services:
  nextjs:
    build: .
    ports:
      - '3000:3000'
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - nextjs
    networks:
      - webnet

networks:
  webnet:
